#!/usr/bin/env ansible-playbook
---
- hosts: hetzner
  vars_files:
  - ../cluster.yml
  tasks:

  - name: Create Cluster Install Marker File 
    file:
        name: "{{ cluster_install_in_progress_marker }}"
        state: touch
      
  - import_role:  
      name: openshift-4-cluster
      tasks_from: prepare-host.yml
